### ISSUE TITLE
Is it safe to ignore the warning about disabled hardening?

### ISSUE THREAD

**Issue by antermin** [cyberus-technology/virtualbox-kvm#12]
From https://github.com/gentoo/gentoo/pull/35258, it seems that `--disable-hardening` is needed, otherwise it still requires the vboxdrv module.

At the same time, there is a warning if you use `--disable-hardening`. Is it safe to ignore the warning?

https://github.com/cyberus-technology/virtualbox-kvm/blob/0396965179fdfb49c87ab49cc77b4e81fd42e0a7/configure#L3142-L3160

**Comment by thesamesam** [comment]
cc @ceamac

**Comment by parthy** [comment]
Just to clarify: Our instructions including disabling hardening are mainly because that's how we know it's possible to run the freshly built binaries. We are not recommending to ignore warnings or deviate from standard procedures out there when packaging VirtualBox for production use.

That being said, the proper packaging is currently not our main focus, so we are also not too experienced with it. If there is anything in the code that we need to fix, we are happy to assist.

**Comment by parthy** [comment]
Just to let everyone know, we have now included more information in the readme. Feel free to have a look and let us know if that clarifies things!

**Comment by tpressure** [comment]
This issue is now tracked in #23
