### ISSUE TITLE
Regarding source code structure, commit history, and code release archives

### ISSUE THREAD

**Issue by antermin** [cyberus-technology/virtualbox-kvm#18]
Previously, the repository contains the full source code of VirtualBox KVM.
However, with the introduction of SR-IOV graphics support:

1. The commit history has been wiped / overwritten
2. Instead of source code, the repository now contains patch sets
3. Release archives in https://github.com/cyberus-technology/virtualbox-kvm/releases are also affected as well. (`virtualbox-kvm-dev-20240226.tar.gz`: full source code, `virtualbox-kvm-dev-20240307.tar.gz`: patch sets)

In the future, will the repository be subjected to these kinds of changes again?
What are your recommendations for packagers who maintain virtualbox-kvm packages (to make updating easier)?

**Comment by tpressure** [comment]
Hi @antermin,

you are completely correct. With our SR-IOV release, we have changed the repository to only include the necessary patches against upstream VirtualBox instead of the full source. We know that this will make packaging not as easy as it was before, but it was a necessary step for us going forward.

> In the future, will the repository be subjected to these kinds of changes again?

We have no intention of changing this again, but of course I cannot make any promises in this regard. Is there a good way to ping packagers beforehand? If so, what process would you suggest?

>  What are your recommendations for packagers who maintain virtualbox-kvm packages (to make updating easier)?

The current recommendation is to pull the VirtualBox source code from directly from Oracle and apply the patches that are provided in our repository. We updated the README.md accordingly.

Regarding the old code history: you can still access it via a release tag if you want to.

**Comment by antermin** [comment]
> Is there a good way to ping packagers beforehand? If so, what process would you suggest?

I am not sure but [Repology's page for virtualbox-kvm](https://repology.org/project/virtualbox-kvm/versions) may be helpful.

At the time of writing, VirtualBox KVM is available in AUR (community-driven repository for Arch Linux, which is unofficial), and in official Gentoo (+ its derivative LiGurOS) repository.

For the Gentoo package maintainer, you can ping `ceamac` on GitHub,
while for the AUR package maintainer, there is also a GitHub profile with the same name (`xyzzy`) but it is not sure whether it belongs to `xyzzy` on AUR.

**Comment by parthy** [comment]
Just for completeness: There is also a single, complete patch file attached to every release so far. This was done with the intention to simplify packaging (example: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/virtualization/virtualbox/default.nix#L117).
