### ISSUE TITLE
Is Intel GVT-g supported? If so, how to set up?

### ISSUE THREAD

**Issue by antermin** [cyberus-technology/virtualbox-kvm#7]
### Bug Description

I noticed that 471c213b5c13f6e25ed7af4b47472296a04bc871 mentioned GVT.

With QEMU/KVM and Intel GVT-g, a Windows guest can have better graphics performance.

Is it possible to use Intel GVT-g with VirtualBox KVM?
If yes, can you please document the steps?

**Comment by tpressure** [comment]
Unfortunately, Intel GVT-g is dead technology and has lots of issues which prevents it from being used in production (see https://github.com/intel/gvt-linux/issues/153 and https://github.com/intel/gvt-linux/issues/188). 

We had support for it a while ago, but dropped it because these issues will never be fixed by Intel.
